pull_request_rules:
  - name: Automatic merge on approval label and CI success
    conditions:
      - base=main
      - label="merge"
      - status-success=build
      - "#review-requested=0"
    actions:
      merge:
        method: squash

  # - name: Automatic merge Dependabot PRs on CI success
  #   conditions:
  #     - base=main
  #     - author=dependabot[bot]
  #     - status-success=build
  #     - "#review-requested=0"
  #     - -dependabot-dependency-name~=org.scala-lang
  #   actions:
  #     merge:
  #       method: squash
